services:
  spotify:
    ports:
      - "127.0.0.1:8083:8083"

  weather:
    ports:
      - "127.0.0.1:8082:8082"

  rss:
    ports:
      - "127.0.0.1:8085:8085"

  quote:
    ports:
      - "127.0.0.1:8086:8086"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - TASKS_URL=http://tasks:8081
      - SPOTIFY_URL=http://spotify:8083
      - WEATHER_URL=http://weather:8082
      - PHOTOS_URL=http://photos:8084
      - RSS_URL=http://rss:8085
      - QUOTE_URL=http://quote:8086
      - HMR_CLIENT_PORT=80
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: sync
          path: ./frontend/static
          target: /app/static
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/svelte.config.js
        - action: rebuild
          path: ./frontend/vite.config.ts
