services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - TASKS_URL=http://tasks:8081
      - HMR_CLIENT_PORT=80
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: sync
          path: ./frontend/static
          target: /app/static
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/svelte.config.js
        - action: rebuild
          path: ./frontend/vite.config.ts
