export const themes = [
    {
        id: 'ash',
        label: 'Ash',
        fill: '#1d1d1d',
        stroke: '#6a6a6a',
        group: 'Black & White',
        colors: {
            bg: '#131313',
            surface: '#1d1d1d',
            surfaceHi: '#282828',
            border: '#383838',
            text1: '#f2f2f2',
            text2: '#9a9a9a',
            text3: '#6a6a6a',
            accent: '#f2f2f2',
        },
    },
    {
        id: 'chalk',
        label: 'Chalk',
        fill: '#ebebeb',
        stroke: '#909090',
        group: 'Black & White',
        colors: {
            bg: '#f5f5f5',
            surface: '#ebebeb',
            surfaceHi: '#e0e0e0',
            border: '#cccccc',
            text1: '#131313',
            text2: '#606060',
            text3: '#909090',
            accent: '#131313',
        },
    },
    {
        id: 'smoke',
        label: 'Smoke',
        fill: '#282828',
        stroke: '#787878',
        group: 'Black & White',
        colors: {
            bg: '#1e1e1e',
            surface: '#282828',
            surfaceHi: '#333333',
            border: '#444444',
            text1: '#eeeeee',
            text2: '#aaaaaa',
            text3: '#787878',
            accent: '#eeeeee',
        },
    },
    {
        id: 'blush',
        label: 'Blush',
        fill: '#f5e8e8',
        stroke: '#b87878',
        group: 'Color',
        colors: {
            bg: '#fdf5f5',
            surface: '#f5e8e8',
            surfaceHi: '#ecdcdc',
            border: '#d8c0c0',
            text1: '#2e1a1a',
            text2: '#9a6060',
            text3: '#b87878',
            accent: '#2e1a1a',
        },
    },
    {
        id: 'dusk',
        label: 'Dusk',
        fill: '#151b2a',
        stroke: '#4e5478',
        group: 'Color',
        colors: {
            bg: '#0d1019',
            surface: '#151b2a',
            surfaceHi: '#1d263c',
            border: '#263050',
            text1: '#d8dcf0',
            text2: '#7278a0',
            text3: '#4e5478',
            accent: '#d8dcf0',
        },
    },
    {
        id: 'forest',
        label: 'Forest',
        fill: '#192118',
        stroke: '#4a6845',
        group: 'Color',
        colors: {
            bg: '#111713',
            surface: '#192118',
            surfaceHi: '#222e20',
            border: '#2e3e2a',
            text1: '#ccddc8',
            text2: '#6a9060',
            text3: '#4a6845',
            accent: '#ccddc8',
        },
    },
    {
        id: 'frost',
        label: 'Frost',
        fill: '#e5ecf2',
        stroke: '#7a98b4',
        group: 'Color',
        colors: {
            bg: '#f2f5f8',
            surface: '#e5ecf2',
            surfaceHi: '#d8e4ee',
            border: '#c0d0de',
            text1: '#1a2430',
            text2: '#6080a0',
            text3: '#7a98b4',
            accent: '#1a2430',
        },
    },
    {
        id: 'linen',
        label: 'Linen',
        fill: '#f0e8da',
        stroke: '#9e8c75',
        group: 'Color',
        colors: {
            bg: '#faf6ef',
            surface: '#f0e8da',
            surfaceHi: '#e8ddd0',
            border: '#d4c9b8',
            text1: '#2a2018',
            text2: '#7a6a55',
            text3: '#9e8c75',
            accent: '#2a2018',
        },
    },
    {
        id: 'plum',
        label: 'Plum',
        fill: '#261118',
        stroke: '#7a3850',
        group: 'Color',
        colors: {
            bg: '#18090e',
            surface: '#261118',
            surfaceHi: '#321620',
            border: '#4a2030',
            text1: '#f0d8e0',
            text2: '#b05870',
            text3: '#7a3850',
            accent: '#f0d8e0',
        },
    },
    {
        id: 'sage',
        label: 'Sage',
        fill: '#e2ece0',
        stroke: '#6e9068',
        group: 'Color',
        colors: {
            bg: '#eef4ec',
            surface: '#e2ece0',
            surfaceHi: '#d4e2d2',
            border: '#b4ccb0',
            text1: '#1a2818',
            text2: '#507050',
            text3: '#6e9068',
            accent: '#1a2818',
        },
    },
    {
        id: 'sky',
        label: 'Sky',
        fill: '#dce8f4',
        stroke: '#6888b0',
        group: 'Color',
        colors: {
            bg: '#eaf1f8',
            surface: '#dce8f4',
            surfaceHi: '#cddcee',
            border: '#adc4de',
            text1: '#162030',
            text2: '#4a6a90',
            text3: '#6888b0',
            accent: '#162030',
        },
    },
    {
        id: 'slate',
        label: 'Slate',
        fill: '#191e24',
        stroke: '#4a6070',
        group: 'Color',
        colors: {
            bg: '#111518',
            surface: '#191e24',
            surfaceHi: '#22292e',
            border: '#2e3a40',
            text1: '#d8e4ec',
            text2: '#6a8090',
            text3: '#4a6070',
            accent: '#d8e4ec',
        },
    },
    {
        id: 'stone',
        label: 'Stone',
        fill: '#26201a',
        stroke: '#806050',
        group: 'Color',
        colors: {
            bg: '#1a1410',
            surface: '#26201a',
            surfaceHi: '#332b23',
            border: '#4a3d34',
            text1: '#ede4d6',
            text2: '#b09878',
            text3: '#806050',
            accent: '#ede4d6',
        },
    },
    {
        id: 'terracotta',
        label: 'Terracotta',
        fill: '#ece0d0',
        stroke: '#ac7850',
        group: 'Color',
        colors: {
            bg: '#f5ede2',
            surface: '#ece0d0',
            surfaceHi: '#e0d0bc',
            border: '#c8b89e',
            text1: '#3a2010',
            text2: '#8a5c38',
            text3: '#ac7850',
            accent: '#3a2010',
        },
    },
    {
        id: 'tide',
        label: 'Tide',
        fill: '#142028',
        stroke: '#2e6868',
        group: 'Color',
        colors: {
            bg: '#0c1416',
            surface: '#142028',
            surfaceHi: '#1c2c34',
            border: '#243c44',
            text1: '#c4dde4',
            text2: '#4a9090',
            text3: '#2e6868',
            accent: '#c4dde4',
        },
    },
] as const;

export type Theme = (typeof themes)[number];
export type ThemeId = Theme['id'];
export type ThemeGroup = Theme['group'];

export const DEFAULT_THEME: ThemeId = themes[0].id;
export const THEME_GROUPS: ThemeGroup[] = [...new Set(themes.map((theme) => theme.group))];

export function isValidThemeId(value: string | null): value is ThemeId {
    return !!value && themes.some((t) => t.id === value);
}
