<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>tasks</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data.Abstractions\Data.Abstractions.csproj" />
    <ProjectReference Include="..\data\Data.csproj" />
  </ItemGroup>

</Project>
